#!/bin/bash

# ============================================================================
# Timecaster Deployment Script
# Deploys contracts and automatically updates frontend with addresses
# ============================================================================

set -e  # Exit on error

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}"
echo "========================================"
echo "  Timecaster Smart Contract Deployment"
echo "========================================"
echo -e "${NC}"

# Check if we're in the right directory
if [ ! -d "contracts" ] || [ ! -d "frontend" ]; then
    echo -e "${RED}Error: Run this script from the project root directory${NC}"
    exit 1
fi

# Check if .env exists
if [ ! -f "contracts/.env" ]; then
    echo -e "${YELLOW}Warning: contracts/.env not found${NC}"
    echo "Creating .env from template..."
    cp contracts/.env.example contracts/.env
    echo -e "${YELLOW}Please edit contracts/.env with your private key and run again${NC}"
    exit 1
fi

# Load environment variables
source contracts/.env

# Check if PRIVATE_KEY is set
if [ -z "$PRIVATE_KEY" ] || [ "$PRIVATE_KEY" = "your_deployer_private_key_here_without_0x" ]; then
    echo -e "${RED}Error: PRIVATE_KEY not set in contracts/.env${NC}"
    exit 1
fi

echo -e "${BLUE}Step 1/4: Building contracts...${NC}"
cd contracts
forge build

if [ $? -ne 0 ]; then
    echo -e "${RED}Build failed!${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Build successful${NC}"
echo ""

echo -e "${BLUE}Step 2/4: Deploying to Base Sepolia...${NC}"
echo -e "${YELLOW}This will deploy 6 contracts and may take 2-3 minutes${NC}"
echo ""

# Deploy contracts
forge script script/Deploy.s.sol:Deploy \
    --rpc-url ${BASE_SEPOLIA_RPC_URL:-https://sepolia.base.org} \
    --broadcast \
    --legacy \
    -vvv \
    | tee deployment.log

if [ $? -ne 0 ]; then
    echo -e "${RED}Deployment failed!${NC}"
    exit 1
fi

echo ""
echo -e "${GREEN}✓ Deployment successful${NC}"
echo ""

echo -e "${BLUE}Step 3/4: Extracting contract addresses...${NC}"

# Extract addresses from deployment log
TREASURY_ADDRESS=$(grep "Treasury deployed at:" deployment.log | awk '{print $NF}')
REPUTATION_ENGINE_ADDRESS=$(grep "ReputationEngine deployed at:" deployment.log | awk '{print $NF}')
FORESIGHT_NFT_ADDRESS=$(grep "ForesightNFT deployed at:" deployment.log | awk '{print $NF}')
CT_DRAFT_ADDRESS=$(grep "CTDraft deployed at:" deployment.log | awk '{print $NF}')
TIMECASTER_ARENA_ADDRESS=$(grep "TimecasterArena deployed at:" deployment.log | awk '{print $NF}')
DAILY_GAUNTLET_ADDRESS=$(grep "DailyGauntlet deployed at:" deployment.log | awk '{print $NF}')

# Validate addresses
if [ -z "$TREASURY_ADDRESS" ] || [ -z "$TIMECASTER_ARENA_ADDRESS" ]; then
    echo -e "${YELLOW}Warning: Could not extract all addresses from deployment log${NC}"
    echo "Please manually update frontend/src/contracts/addresses.ts"
    exit 0
fi

echo -e "${GREEN}Extracted addresses:${NC}"
echo "Treasury:           $TREASURY_ADDRESS"
echo "ReputationEngine:   $REPUTATION_ENGINE_ADDRESS"
echo "ForesightNFT:       $FORESIGHT_NFT_ADDRESS"
echo "CTDraft:            $CT_DRAFT_ADDRESS"
echo "TimecasterArena:    $TIMECASTER_ARENA_ADDRESS"
echo "DailyGauntlet:      $DAILY_GAUNTLET_ADDRESS"
echo ""

echo -e "${BLUE}Step 4/4: Updating frontend configuration...${NC}"
cd ..

# Update addresses.ts
cat > frontend/src/contracts/addresses.ts << EOF
/**
 * Contract Addresses
 * Auto-generated by deploy-and-update.sh
 * Last updated: $(date)
 */

export const CONTRACT_ADDRESSES = {
  // Base Sepolia Testnet
  baseSepolia: {
    timecasterArena: '${TIMECASTER_ARENA_ADDRESS}' as \`0x\${string}\`,
    ctDraft: '${CT_DRAFT_ADDRESS}' as \`0x\${string}\`,
    dailyGauntlet: '${DAILY_GAUNTLET_ADDRESS}' as \`0x\${string}\`,
    foresightNFT: '${FORESIGHT_NFT_ADDRESS}' as \`0x\${string}\`,
    reputationEngine: '${REPUTATION_ENGINE_ADDRESS}' as \`0x\${string}\`,
    treasury: '${TREASURY_ADDRESS}' as \`0x\${string}\`,
  },

  // Base Mainnet (for future deployment)
  base: {
    timecasterArena: '0x0000000000000000000000000000000000000000' as \`0x\${string}\`,
    ctDraft: '0x0000000000000000000000000000000000000000' as \`0x\${string}\`,
    dailyGauntlet: '0x0000000000000000000000000000000000000000' as \`0x\${string}\`,
    foresightNFT: '0x0000000000000000000000000000000000000000' as \`0x\${string}\`,
    reputationEngine: '0x0000000000000000000000000000000000000000' as \`0x\${string}\`,
    treasury: '0x0000000000000000000000000000000000000000' as \`0x\${string}\`,
  },
} as const;

// Helper to get addresses for current network
export function getContractAddresses(chainId: number) {
  switch (chainId) {
    case 84532: // Base Sepolia
      return CONTRACT_ADDRESSES.baseSepolia;
    case 8453: // Base Mainnet
      return CONTRACT_ADDRESSES.base;
    default:
      return CONTRACT_ADDRESSES.baseSepolia; // Default to testnet
  }
}
EOF

echo -e "${GREEN}✓ Frontend addresses updated${NC}"
echo ""

echo -e "${GREEN}"
echo "========================================"
echo "  Deployment Complete! 🎉"
echo "========================================"
echo -e "${NC}"

echo "Contract Addresses:"
echo "-------------------"
echo "Treasury:           $TREASURY_ADDRESS"
echo "ReputationEngine:   $REPUTATION_ENGINE_ADDRESS"
echo "ForesightNFT:       $FORESIGHT_NFT_ADDRESS"
echo "CTDraft:            $CT_DRAFT_ADDRESS"
echo "TimecasterArena:    $TIMECASTER_ARENA_ADDRESS"
echo "DailyGauntlet:      $DAILY_GAUNTLET_ADDRESS"
echo ""

echo -e "${BLUE}Next Steps:${NC}"
echo "1. Verify contracts on Basescan:"
echo "   https://sepolia.basescan.org/address/$TIMECASTER_ARENA_ADDRESS"
echo ""
echo "2. Test the frontend:"
echo "   cd frontend && pnpm dev"
echo ""
echo "3. View on Base Sepolia:"
echo "   https://sepolia.basescan.org"
echo ""

# Save addresses to a file for reference
cat > deployment-addresses.json << EOF
{
  "network": "Base Sepolia",
  "chainId": 84532,
  "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "contracts": {
    "treasury": "$TREASURY_ADDRESS",
    "reputationEngine": "$REPUTATION_ENGINE_ADDRESS",
    "foresightNFT": "$FORESIGHT_NFT_ADDRESS",
    "ctDraft": "$CT_DRAFT_ADDRESS",
    "timecasterArena": "$TIMECASTER_ARENA_ADDRESS",
    "dailyGauntlet": "$DAILY_GAUNTLET_ADDRESS"
  }
}
EOF

echo -e "${GREEN}✓ Deployment info saved to deployment-addresses.json${NC}"
